version: '3'

volumes:
  app-data:
    driver: local

services:

  database:
    image: mysql:5.7.22
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Sao_Paulo


  app:
    image: ambientum/php:7.3-nginx
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:8080"
    environment:
      - XDEBUG_CONFIG="remote_host=localhost remote_port=9000"
      - XDEBUG_ENABLED=true
    links:
      - database